name: Node.js Package

on:
  release:
    types: [published]

jobs:
  run-publishing:
    uses: .github/workflows/publish.yml
    with:
      tag: ${{ github.event.release.tag_name }}
      prerelease: ${{ github.event.release.prerelease }}
    secrets: inherit
