name: Publish on Release

on:
  release:
    types: [published]

jobs:
  run-publishing:
    uses: ./.github/workflows/publish.yml
    with:
      prerelease: ${{ github.event.release.prerelease }}
    secrets: inherit
